In [1]:
import scipy.optimize as optimize

In [5]:
alpha = 1/95000
def F(x):
    return alpha*(x**2-900**2)/2

In [10]:
def f(params):
    b1, b2 = params
    return -((1000-b1)*F(b1) + (1000-b2)*(F(b2)-F(b1)))

initial_guess = [900+100/3, 900+100/3*2]
result = optimize.minimize(f, initial_guess)

In [11]:
result.x

array([933.93565136, 967.25468189])

In [106]:
import numpy as np

n=200000
n_goldfishes = 10000

goldfishes = np.sqrt(2*np.random.uniform(0,1,size=(n,n_goldfishes))/alpha+900**2)
bids = np.random.uniform(900,1000,size=(n,2))

In [107]:
bids.sort(axis=1)

In [108]:
payoffs = np.where(goldfishes<bids[:,:1],1000-bids[:,:1],np.where(goldfishes<bids[:,1:], 1000-bids[:,1:], 0))
payoffs.mean(axis=1).mean()

24.36910921272903

In [125]:
bids[np.argsort(((bids-np.array([933.93, 967.25]))**2).sum(axis=1))][0:100]

array([[933.94877728, 967.21440324],
       [933.94041861, 967.19380598],
       [933.87181278, 967.21196391],
       [934.0193698 , 967.18111056],
       [933.76309966, 967.17533313],
       [933.84307935, 967.08459646],
       [933.79104153, 967.07503622],
       [933.94028258, 967.02038919],
       [934.06143558, 967.45123269],
       [934.03232737, 967.47353259],
       [934.12288709, 967.43439912],
       [933.70438656, 967.42215122],
       [934.2160275 , 967.34124618],
       [933.68917326, 967.4473062 ],
       [933.93972189, 966.92701332],
       [933.64018821, 967.3929875 ],
       [934.26108486, 967.06405134],
       [934.03460173, 967.62329425],
       [934.32780404, 967.19454064],
       [934.28926549, 967.05929184],
       [933.7617998 , 967.63292696],
       [934.35982288, 967.17799229],
       [934.07078186, 966.83360346],
       [933.53267573, 967.02131867],
       [933.58433771, 966.94137367],
       [934.31840218, 966.98100302],
       [933.96119352, 967.73252412],
 

In [110]:
bids[payoffs.mean(axis=1).argmax()]

array([933.01990854, 971.03713715])

In [121]:
n=1000
n_goldfishes=100000
goldfishes = np.sqrt(2*np.random.uniform(0,1,size=(n,n_goldfishes))/alpha+900**2)
best_bids = [933.01990854, 971.03713715]
payoffs = np.where(goldfishes<best_bids[0],1000-best_bids[0],np.where(goldfishes<best_bids[1], 1000-best_bids[1], 0))
payoffs.mean(axis=1).mean()

32.37422059257855