In [3]:
import numpy as np

In [4]:
prizes = np.array([24,70,41,21,60,47,82,87,80,35,73,89,100,90,17,77,83,85,79,55,12,27,52,15,30])*7500
hunters = np.array([2,4,3,2,4,3,5,5,5,3,4,5,8,7,2,5,5,5,5,4,2,3,4,2,3])
# prizes = prizes[np.argsort(prizes)][::-1]

In [158]:
import plotly_express as px

In [178]:
px.line((prizes/np.roll(prizes,1))[1:])

In [179]:
px.line(prizes)

In [10]:
def count_choices(x):
    x=x.reshape(-1)
    count = np.zeros(len(prizes))
    for i in range(len(prizes)): 
        count[i] = np.count_nonzero(x==i)
    return count/sum(count)*100

In [251]:
n_persons = 3000

choices = np.full([n_persons,3],-1)

mean_returns = []

In [261]:
for i in range(10):
    for p in range(n_persons):
        if np.random.uniform()>1:
            person_choices = np.random.choice(np.arange(0,len(prizes)),3)
        else: 
            payoffs = prizes/(count_choices(choices)+hunters)
            person_choices = np.argpartition(payoffs,-3)[-3::][::-1]
        # if payoffs[1]>25000:
        #     if payoffs[2]<75000:
        #         person_choices = np.concatenate([person_choices[0:2],[-1]])
        # else: 
        #     person_choices=np.concatenate([person_choices[0:1],[-1,-1]])
        choices[p,:] = person_choices

    total_returns = 0 
    payoffs = prizes/np.maximum(count_choices(choices),1)
    for p in range(n_persons):
        total_returns += sum(payoffs[choices[p]])

    mean_returns.append(total_returns/n_persons)
# person_choices =  np.argsort(payoffs)

In [253]:
prizes

array([180000, 525000, 307500, 157500, 450000, 352500, 615000, 652500,
       600000, 262500, 547500, 667500, 750000, 675000, 127500, 577500,
       622500, 637500, 592500, 412500,  90000, 202500, 390000, 112500,
       225000])

In [262]:
count_choices(choices)

array([1.33333333, 5.77777778, 2.77777778, 0.88888889, 4.33333333,
       3.55555556, 6.44444444, 7.11111111, 6.11111111, 1.88888889,
       6.22222222, 7.33333333, 6.        , 5.55555556, 0.44444444,
       5.77777778, 6.55555556, 6.88888889, 6.        , 3.55555556,
       0.        , 0.77777778, 3.33333333, 0.11111111, 1.22222222])

In [223]:
count_choices(choices)

array([1.35, 5.75, 2.75, 0.95, 4.35, 3.55, 6.45, 7.15, 6.15, 1.9 , 6.2 ,
       7.4 , 5.9 , 5.55, 0.4 , 5.75, 6.6 , 6.8 , 6.  , 3.7 , 0.  , 0.8 ,
       3.25, 0.1 , 1.2 ])

In [249]:
px.histogram(prizes,nbins=len(prizes))

In [263]:
payoffs[choices[np.argmax([sum(payoffs[choice]) for choice in choices])]]

array([202500.        , 138970.58823529,  98750.        ])

In [264]:
px.histogram([sum(payoffs[choice]) for choice in choices])

In [265]:
payoffs

array([135000.        ,  90865.38461538, 110700.        , 157500.        ,
       103846.15384615,  99140.625     ,  95431.03448276,  91757.8125    ,
        98181.81818182, 138970.58823529,  87991.07142857,  91022.72727273,
       125000.        , 121500.        , 127500.        ,  99951.92307692,
        94957.62711864,  92540.32258065,  98750.        , 116015.625     ,
        90000.        , 202500.        , 117000.        , 112500.        ,
       184090.90909091])